### ISSUE TITLE
Upload folder from computer client

### ISSUE THREAD

**Issue by levantuy** [mgilangjanuar/teledrive#138]
**Is your feature request related to a problem? Please describe.**
Same feature google driver

**Comment by mgilangjanuar** [comment]
Can you elaborate on this request?

**Comment by mgilangjanuar** [comment]
Did you mean upload folder like this?
![image](https://user-images.githubusercontent.com/3146378/146169099-2838d585-9ab0-4efd-8e3c-80dd29431efa.png)

**Comment by mahdiarn** [comment]
I think what @levantuy meant is upload folder feature in the google drive

<img width="231" alt="Screen Shot 2022-01-09 at 22 58 52" src="https://user-images.githubusercontent.com/18479742/148690129-45a33894-e9ee-4377-bee2-244d021db74c.png">

I test it on the teledrive when I tried to upload a directory with a file inside it, here's the directory structure:

<img width="500" alt="Screen Shot 2022-01-09 at 23 00 29" src="https://user-images.githubusercontent.com/18479742/148690197-5db9abcb-23d7-4f3e-9a7a-6b3a0a1b466f.png">

The differences between teledrive and google maps, when we click "Upload Folder" in google drive and select a folder, the folder with its content is uploaded to the drive

<img width="367" alt="Screen Shot 2022-01-09 at 22 57 30" src="https://user-images.githubusercontent.com/18479742/148690263-e010042e-d259-4b3f-9d07-3aa6893f7621.png">

But in teledrive, when I tried to upload a folder, the one that are uploaded are the contents of the folder only

<img width="191" alt="Screen Shot 2022-01-09 at 22 57 39" src="https://user-images.githubusercontent.com/18479742/148690323-25aebcca-c8b7-4ef1-b715-fa9362705d65.png">

**Comment by mgilangjanuar** [comment]
Ah, I see, lemme figure it out then. Thanks!

**Comment by mgilangjanuar** [comment]
https://user-images.githubusercontent.com/3146378/148726072-5c052226-78e8-4cf5-ba5a-3fe06b463ce0.mov
