### ISSUE TITLE
Installation with Repl or Ubuntu Server

### ISSUE THREAD

**Issue by MaximilianGT500** [mgilangjanuar/teledrive#198]
Hello, how can i install teledrive with Ubuntu 20.04 or Repl.IT?
Im stuck in the installation.

Thanks,
Max

**Comment by MaximilianGT500** [comment]
Okay, i try it.

**Comment by MaximilianGT500** [comment]
How can i get an SQL File for the Database, i can´t use the command with the Manager from AAPanel

**Comment by mgilangjanuar** [comment]
Did you just run `yarn server typeorm schema:sync`?

**Comment by MaximilianGT500** [comment]
Yes, this is not working.

**Comment by mgilangjanuar** [comment]
Hmm try to manual import from the SQL file here: https://github.com/mgilangjanuar/teledrive/blob/staging/server/src/model/migrations/dump.sql

**Comment by MaximilianGT500** [comment]
Yes, thanks now all is working.
