### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by daca11** [mgilangjanuar/teledrive#199]
It would be great to have a docker image with configurable env vars, so that you don't need to have the requisites installed on your local machine and get started fast.

**Comment by mgilangjanuar** [comment]
Yes, already on a backlog and will find the best time to do it 😅

Related #188

**Comment by prakashdivyy** [comment]
@daca11 waiting for review https://github.com/mgilangjanuar/teledrive/pull/257

**Comment by daca11** [comment]
I was looking for a pre-build docker image, but that's a good starting point!

**Comment by mgilangjanuar** [comment]
Done and tested 🎊
