### ISSUE TITLE
Update token is required

### ISSUE THREAD

**Issue by MaximilianGT500** [mgilangjanuar/teledrive#208]
When I try to log in now comes the error message: Update token is required

**Comment by mgilangjanuar** [comment]
Can you screenshot the log errors?

**Comment by MaximilianGT500** [comment]
https://i.m16k.de/bilder-storage/nsChjWBbCAT0oGIKdTcuL9PkNKyVg5at-1267x316.png
https://i.m16k.de/bilder-storage/7dgA1I3IVcJlcW9m9FWswUHEgmSqyVRx-1267x547.png

**Comment by mgilangjanuar** [comment]
Oh, it's from /refreshToken endpoint. That is automatically called if you're not logged in: https://github.com/mgilangjanuar/teledrive/blob/8e2957bbd2fc1c1c45ef04523af0aa74550f85b8/server/src/api/v1/Auth.ts#L120

You can ignore it.

**Comment by MaximilianGT500** [comment]
Yea, but i can´t log me in:
https://i.m16k.de/bilder-storage/t666o55Wsujjdw1KtlOOGZm0HNK6E4xA-1920x937.png

**Comment by mgilangjanuar** [comment]
Hmm I noticed there's an error when you hit /login, seems your browser not enable cookies for your site: https://github.com/mgilangjanuar/teledrive/blob/cabc5e890d6f4f859e16f8c99854c1b7277d1cc8/server/src/api/middlewares/Auth.ts#L9-L12

**Comment by MaximilianGT500** [comment]
Yea, i think i found the Error. I test it

**Comment by MaximilianGT500** [comment]
It use my old Domain for the Requests: 
Anfrage-URL: https://MYOLDDOMAIN/api/v1/utils/ipinfo

**Comment by mgilangjanuar** [comment]
Oh you should use the same domain for web and server API

**Comment by MaximilianGT500** [comment]
Exactly that is the punk it is confused that he uses my other domain although I use the new one

**Comment by MaximilianGT500** [comment]
It´s working i rebuild it and i think it was:
/web/.env
REACT_APP_API_URL=https://URL

**Comment by mgilangjanuar** [comment]
Good 👍
