### ISSUE TITLE
Upgrade / Updating

### ISSUE THREAD

**Issue by MaximilianGT500** [mgilangjanuar/teledrive#212]
Hello, i can´t upgrade the project with: "node upgrade.js"
https://i.m16k.de/bilder-storage/XPcuOV7NBAODJf6r08qrm2pIFYJRn6Be-634x754.png

**Comment by mgilangjanuar** [comment]
For upgrading app, you have to add a version as args, eg `node upgrade.js 1.7.2`

**Comment by MaximilianGT500** [comment]
Will my whole code be changed then, because I have translated the complete code?

**Comment by mgilangjanuar** [comment]
Hmm, it's only update the package.json in workspaces. I don't think so 🤔

**Comment by MaximilianGT500** [comment]
Okay, thanks. Another small question the download speed because Telegram or why I have only 2Mb/s although I normally download from my server with 12Mb/s.

**Comment by mgilangjanuar** [comment]
Maybe there's something from your server to the Telegram https://github.com/mgilangjanuar/teledrive/blob/02131781096f213babef850094f8f480b1fe125a/server/src/api/v1/Files.ts#L563

**Comment by MaximilianGT500** [comment]
Ah okay, thanks. Can i make an new issue for a Future Request?

**Comment by mgilangjanuar** [comment]
Sure, I'll close this one 👍
