### ISSUE TITLE
Need some improvements in page navigation

### ISSUE THREAD

**Issue by raniaamina** [mgilangjanuar/teledrive#216]
Thanks for creating awesome service for us.

The thing that I think strange is, when I've logged in and then move away from the dashboard page, I lose my way back to my dashboard quickly. I have to go back to the home page and then back looking for a button to go back to my dashboard. Isn't this a little weird?

Some options that I think could be taken are to display a single button/menu that appears on all pages after the user logs into their account (for example, i add a new menu in navigation). 

![gambar](https://user-images.githubusercontent.com/22146607/149807044-99842997-b16d-421a-8482-718ef4867b03.png)

I know it not to good, but hope you get my point.

Thanks,
Rania Amina

**Comment by mgilangjanuar** [comment]
Good idea! Actually, the dashboard menu is under the profile button in the right top corner. We'll move that 😅

**Comment by raniaamina** [comment]
Hmm I found it, my bad.
Just wanna make it more accessable :")

Thanks

**Comment by mgilangjanuar** [comment]
![image](https://user-images.githubusercontent.com/3146378/150624997-ced443b3-27ff-4336-81d6-013ab63a218c.png)

I move out the Dashboard menu on the new version 😄

**Comment by raniaamina** [comment]
Great! 
Thanks for improvement!
