### ISSUE TITLE
Add the possibility to share folders.

### ISSUE THREAD

**Issue by ZeroDot1** [mgilangjanuar/teledrive#222]
Add the possibility to share folders with multiple files.
This is very helpful when organizing files to be shared.

**Comment by mgilangjanuar** [comment]
Hello, do you mean like this? https://teledriveapp.com/view/98619ea2-acc0-4e58-a534-724e327a112e

**Comment by ZeroDot1** [comment]
Exactly, but with multiple files, when I want to share a folder in the current version 1.8.0 the share dialog closes and I do not get a link.

**Comment by mgilangjanuar** [comment]
Yes, I added more files to it. Hmm that's weird can you screen recording the bug? 🤔

**Comment by ZeroDot1** [comment]
Unfortunately I can not record the bug, my screen recorder does not work correctly, the recorded video flickers.

And now I can't access it anymore....
![Bildschirmfoto vom 2022-01-20 13-59-30](https://user-images.githubusercontent.com/28985171/150343664-dcf790a3-3c8f-46ac-a343-ab7b08de2860.png)

**Comment by ZeroDot1** [comment]
Video: https://teledriveapp.com/view/d48f9471-3474-4af4-8418-ae919c2d8b17

**Comment by mgilangjanuar** [comment]
Err, the CPU and traffic are high this night. Can you reload again? 
Oh, the sharing folder is a premium feature anyway.

**Comment by ZeroDot1** [comment]
OK, then I have to save money so that I can buy the premium features, at the moment it is unfortunately not possible for me.

**Comment by mgilangjanuar** [comment]
You also can deploy on your own server by following the instructions in README.md.
