### ISSUE TITLE
Files are not deleted from saved messages

### ISSUE THREAD

**Issue by LucaArietti** [mgilangjanuar/teledrive#228]
**Describe the bug**
If you select for deletion a file in the root and an entire folder from teledrive, the files inside that folder in teledrive are not deleted from saved messages. Anyway, the selected things are removed from teledrive.

**To Reproduce**
1. From teledrive, select a file in the root folder and an entire folder
2. Click on Delete, checking the flag to delete files in telegram saved messages, too
3. On teledrive, is all ok
4. In the saved messages in telegram, the files that were inside the folder, persists
5. The files that were in the root teledrive folder, are correctly deleted, also from telegram

ps: really thank you for your nice project!

**Comment by mgilangjanuar** [comment]
Oh yea, I missed that 🙏

**Comment by mgilangjanuar** [comment]
I remove that option because too many edge cases to do that thing

![image](https://user-images.githubusercontent.com/3146378/151686462-4204ffe2-ad0e-4b0e-978e-f354dfb1e86e.png)
