### ISSUE TITLE
Problem with file availability

### ISSUE THREAD

**Issue by BerkerSP** [mgilangjanuar/teledrive#238]
**Describe the bug**
The problem is that while the account is open on the site, the file can be accessed publicly without any problem, but at the same time, when you log out, it is no longer available.

**To Reproduce**
1. Login
2. Upload a file and set it up publicly
3. Log out
4. File not available

**Expected behavior**
Ideally, when validating a session, it should be kept open and the file should be available, since at least in my case I log in 3 times and I always have to log in again for the file to be available.

**Screenshots**
I didn't get to take a picture, but it included a Cloudflare error where it marked the TeleDrive domain as "host error", but when I logged in, the screen no longer appeared.

**Desktop (please complete the following information):**
 - OS: All of them
 - Browser All of them
 - Version All of them

**Smartphone (please complete the following information):**
 - Same as above, all of them

**Additional context**
It would be excellent if the session could be persistent and only be logged in once, or when manually logging out. Likewise, could you also look at the problem of the videos that when trying to fast forward or rewind they restart? Thanks, excellent project!

**Comment by mgilangjanuar** [comment]
Once you log out the confirmation is popup for confirm to destroy the session. So, all shareable files are can't to downloaded by others again. We'll try to implement the options for log out confirmation to destroy or not the session for this issue 🤔 

![image](https://user-images.githubusercontent.com/3146378/151685435-8a9c59fa-1660-475b-abd4-0c6e78d0cccf.png)

**Comment by BerkerSP** [comment]
Thanks for your fast reply! My main issue related to this is sometimes the sessions get logout alone without me touching nothing, it dissappear from Telegram Sessions too, and when i check in TeleDrive it's gone too, there are some time-limitator for sessions? Thanks!

**Comment by mgilangjanuar** [comment]
Hmm weird how long you didn't open the TeleDrive?

**Comment by BerkerSP** [comment]
I used TeleDrive yesterday and didn't login for some like 15hs and still nice, but today i stopped use this for near 6 hours and the session wasn't able and need login again

**Comment by mgilangjanuar** [comment]
If the session is expired, it will not remove the active session in Telegram. I'll check for the next 24h.

**Comment by mgilangjanuar** [comment]
I think it's resolved, please re-open this if you have any issues related to this.
