### ISSUE TITLE
Sonyliv not login through otp

### ISSUE THREAD

**Issue by Netlivtv** [mgilangjanuar/teledrive#239]
How can i login sonyliv with otp

**Comment by mgilangjanuar** [comment]
If you mean OTP is a Two-Step Verification, you can input your 2FA password after inputting the code from your Telegram app

![image](https://user-images.githubusercontent.com/3146378/151685512-541158ae-4f76-48c3-80b9-3ecce2a70209.png)

And this is how to set up your 2FA: https://telegram.org/blog/sessions-and-2-step-verification

**Comment by Netlivtv** [comment]
I want to download sonyliv premium content
But sonyliv won't login in bot

**Comment by mgilangjanuar** [comment]
I don't understand. What the sonyliv is?

**Comment by Netlivtv** [comment]
I am taking about this

**Comment by Netlivtv** [comment]
![Uploading IMG_20220131_155231.jpg…]()
I am taking about this

**Comment by mgilangjanuar** [comment]
I think you should ask to the SonyLIV team.
