### ISSUE TITLE
Get premium on self hosted instance?

### ISSUE THREAD

**Issue by Nixuge** [mgilangjanuar/teledrive#278]
Hi, I've been fiddling with teledrive for a bit and got it working, but i'm trying to find a way to get premium on self hosted instances. Tried to change "free" to "premium" in postgre and changing a few things but nothing seem to be working. Did anyone succeed in doing this?
Thanks.

**Comment by mgilangjanuar** [comment]
Try to remove these lines: https://github.com/mgilangjanuar/teledrive/blob/staging/server/src/api/v1/Users.ts#L185-L220

I'll create a new branch to remove all restrictions for self-host

**Comment by RehanPlayz** [comment]
> Try to remove these lines: https://github.com/mgilangjanuar/teledrive/blob/staging/server/src/api/v1/Users.ts#L185-L220
> 
> I'll create a new branch to remove all restrictions for self-host

I'm also interested in running teledrive self-hosted with premium enabled, Any update on the new branch with restrictions removed?

**Comment by Nixuge** [comment]
> > Try to remove these lines: https://github.com/mgilangjanuar/teledrive/blob/staging/server/src/api/v1/Users.ts#L185-L220
> > I'll create a new branch to remove all restrictions for self-host
> 
> I'm also interested in running teledrive self-hosted with premium enabled, Any update on the new branch with restrictions removed?

Seems like he added an option just for this in commit #11a8e158f71f10a69019ee98ae6a8c76e22b858d, now it's in the config file directly, thanks @mgilangjanuar

**Comment by oddmario** [comment]
I don't get it. I've set the environment variable to true and I'm still confused on what should I do to grant myself premium access
Would appreciate it so much if this project gets optimized to work as a self-hosted solution since its currently full of hard-coded lines
