### ISSUE TITLE
Installation on UbuntuServer 20.04.4

### ISSUE THREAD

**Issue by EtorS** [mgilangjanuar/teledrive#282]
Hi, i have a problem with installation on Ubuntu Server 20.04.

I installed every requisite, but when i try

`yarn server typeorm schema:sync`

i have this error:

```
yarn run v1.22.17
$ yarn workspace server typeorm schema:sync
error Command "typeorm" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /usr/lib/node_modules/yarn/lib/cli.js typeorm schema:sync
Directory: /home/etors/teledrive/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hivebackup** [comment]
Try to use `psql db_name < ./server/src/model/migrations/dump.sql` instead, had the same issue and using this instead fixed it

**Comment by EtorS** [comment]
> Try to use `psql db_name < ./server/src/model/migrations/dump.sql` instead, had the same issue and using this instead fixed it

No luck.. i got another error.. i need a guide for installation on ubuntu 😥

**Comment by mgilangjanuar** [comment]
Have you tried with docker?

**Comment by EtorS** [comment]
Thanks to a friend i managed to install and run the application! But obviously I have a problem 😅. I can't sing in in telegram, i receive the verification code but the site return a generic error and don't let me put the verification code. I think it's related to API_JWT_SECRET, but I don't know what's its is this variable and simply I leave blank.. what I have to put in those JWT variables? Thanks 🙏

**Comment by mgilangjanuar** [comment]
Cool! It's a random string.

**Comment by mgilangjanuar** [comment]
Try to pull and rebuild everything, I just refactor the whole installation with docker 😆

**Comment by EtorS** [comment]
> Cool! It's a random string.

YEYYYY Finally!! Everything working! But... i cant upload file greater than 2GB, i setted the variable disable payment check but.. i have to do something else? pay? or?

**Comment by mgilangjanuar** [comment]
Did you just update your plan in users db to `premium`?

**Comment by EtorS** [comment]
> Did you just update your plan in users db to `premium`?

Uhm no, I'll try, u can give me more details? Thanks 🙏

**Comment by EtorS** [comment]
> > Did you just update your plan in users db to `premium`?
> 
> Uhm no, I'll try, can you give me more details? Thanks 🙏

Ok, i managed to update the plan to 'premium', but launching the server reset the value to '', I do something wrong?

**Comment by Paulschellnast** [comment]
I get a network error when I try to log in by phone number. The QR code also does not load for me.

> Thanks to a friend i managed to install and run the application! But obviously I have a problem 😅. I can't sing in in telegram, i receive the verification code but the site return a generic error and don't let me put the verification code. I think it's related to API_JWT_SECRET, but I don't know what's its is this variable and simply I leave blank.. what I have to put in those JWT variables? Thanks 🙏

**Comment by mgilangjanuar** [comment]
Weird, can you update the env `DISABLE_PAYMENT_CHECK` to `true`?

**Comment by EtorS** [comment]
> Weird, can you update the env `DISABLE_PAYMENT_CHECK` to `true`?

It's already set to true.. :(

**Comment by EtorS** [comment]
This is my .env file..

`NPM_TOKEN=your_github_token

# server configuration
ENV=production
RPS=

TG_API_ID=nothingtoseehere
TG_API_HASH=nothingtoseehere
TG_BOT_TOKEN=nothingtoseehere
TG_BOT_OWNER_ID=nothingtoseehere
TG_BOT_ERROR_REPORT_ID=

DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_NAME=teledrive

GITHUB_TOKEN=

API_JWT_SECRET=abcd1234
FILES_JWT_SECRET=abcd1234

PAYPAL_CLIENT_ID=
PAYPAL_CLIENT_SECRET=
PAYPAL_PLAN_PREMIUM_ID=

MIDTRANS_MERCHANT_ID=
MIDTRANS_CLIENT_KEY=
MIDTRANS_SERVER_KEY=

UTILS_API_KEY=

DISABLE_PAYMENT_CHECK=true`

**Comment by mgilangjanuar** [comment]
I'll remove all restrictions in a new branch for on-premise installation

**Comment by greengeckowizard** [comment]
This seems to be resolved!!
