### ISSUE TITLE
I want to contribute new features in this app, but need to deploy first on heroku

### ISSUE THREAD

**Issue by starpunjabi** [mgilangjanuar/teledrive#289]
I like your application and concept, and want to contribute to add new features in your application in my free time.
But somehow I am unable to setup it on heroku due to some issues. Can you share installation guide for heroku.
Or How can i directly deploy to heroku from github, if you will add config vars etc. for heroku.
Once it is setup on my heroku account that is connected with my github, i will contribute new features in it.

**Comment by mgilangjanuar** [comment]
I will add Heroku installation in docs

**Comment by mgilangjanuar** [comment]
https://teledriveapp.com/docs/Deployment/heroku

**Comment by starpunjabi** [comment]
> https://teledriveapp.com/docs/Deployment/heroku

Thanks let me deploy it.
