### ISSUE TITLE
Getting Error "Your API ID or Hash cannot be empty or undefined" when joining beta experimental feature."

### ISSUE THREAD

**Issue by AmoghSaxena** [mgilangjanuar/teledrive#296]
My server is working fine in every use case but when i use beta - featrues like fast download. it redirects me to again a login page and when i enter the number to login it shows 
```
Your API ID or Hash cannot be empty or undefined" when joining beta experimental feature.
```

I dont know which API and Hash should we use in `REACT_APP_TG_API_ID` and `REACT_APP_TG_API_HASH`

as  of now I have used same API and Hash that I have used in `TG_API_ID` and `TG_API_HASH`

Please help! 
Thankyou

**Comment by mgilangjanuar** [comment]
build with this command:

`REACT_APP_TG_API_ID=[your_api_id] REACT_APP_TG_API_HASH=[your_api_hash] yarn workspaces run build`

**Comment by mgilangjanuar** [comment]
set the env REACT_APP_TG_API_ID and REACT_APP_TG_API_HASH in docker/.env and rebuild app with `docker-compose up -d --build app`

**Comment by AmoghSaxena** [comment]
> pull the latest update, set the env REACT_APP_TG_API_ID and REACT_APP_TG_API_HASH in docker/.env and rebuild app with `docker-compose up -d --build app`

Yup i am already on the latest commit. Pulled 2 hours ago

**Comment by mgilangjanuar** [comment]
Reload for update and make sure you have v2.0.4

<img width="640" alt="image" src="https://user-images.githubusercontent.com/3146378/160844022-ea545537-e093-4dd3-a1bf-2f945453ee18.png">

**Comment by AmoghSaxena** [comment]
> Reload for update and make sure you have v2.0.4
> 
> <img alt="image" width="640" src="https://user-images.githubusercontent.com/3146378/160844022-ea545537-e093-4dd3-a1bf-2f945453ee18.png">

Yup I am on the latest Version.
![image](https://user-images.githubusercontent.com/13078900/160844708-c57ed9d0-9bef-46c9-96b3-f23e457008b0.png)

**Comment by mgilangjanuar** [comment]
Hmm from which branch do you use?

**Comment by AmoghSaxena** [comment]
> Hmm from which branch do you use?

Main Branch!

**Comment by mgilangjanuar** [comment]
Try with clean install?

**Comment by AmoghSaxena** [comment]
> Try with clean install?

Did now..
Same issue. :(

**Comment by mgilangjanuar** [comment]
pull the latest updates from main branch, remove all related images, do `docker-compose down && docker-compose build teledrive && docker-compose up -d`

**Comment by AmoghSaxena** [comment]
> pull the latest updates from main branch, remove all related images, do `docker-compose down && docker-compose build teledrive && docker-compose up -d`

This time  it went further but raised and error
```
Cannot send requests while disconnected. You need to call .connect()
```

![image](https://user-images.githubusercontent.com/13078900/160995228-af512de1-903c-4251-a350-22bdefd966e8.png)


Although this time I got no error for `Your API ID or Hash cannot be empty or undefined`

**Comment by mgilangjanuar** [comment]
did you setup ssl?

**Comment by AmoghSaxena** [comment]
> did you setup ssl?

No not yet. Should I setup SSL and then try ?

**Comment by mgilangjanuar** [comment]
Yes, maybe it helps

**Comment by AmoghSaxena** [comment]
### Yup ### 
It was an SSL Error for sure!.

Its working like charm now! 
:tada:  Thank you sooo much for helping out in this and giving your valuable time! 

You got a new follower and a sponsor from my side! 
Thanks a lot.

**Comment by oyech** [comment]
tutorial dong gan...

**Comment by oyech** [comment]
> build with this command:
> 
> `REACT_APP_TG_API_ID=[your_api_id] REACT_APP_TG_API_HASH=[your_api_hash] yarn workspaces run build`
> 
> Edit: yes, you should set the same value for TG_API_ID and TG_API_HASH for it, for acknowledged by react app

gmn caranya gan?

**Comment by stepersy** [comment]
![teledrive](https://user-images.githubusercontent.com/94073410/232250358-3a6bc98c-8467-4352-87fc-290cc3495e66.png)
Same problem for me, but I deploy it through Railway (so there's the SSL i think)
