### ISSUE TITLE
Can't access the teledriveapp.com website 

### ISSUE THREAD

**Issue by dzaky-pr** [mgilangjanuar/teledrive#298]
When logging in, I accidentally pressed the german server region which goes to https://ge.teledriveapp.com/ and after opening the initial teledriveapp.com link it goes straight to https://ge.teledriveapp.com/ (permanently)

**Comment by mgilangjanuar** [comment]
clear your cache and localstorage browser

**Comment by mgilangjanuar** [comment]
Yes, that is the new form of TeleDrive homepage, you can install TeleDrive to your server or machine now.
