### ISSUE TITLE
Unable to login by phone number after updating v2.1.0

### ISSUE THREAD

**Issue by mzch** [mgilangjanuar/teledrive#308]
**Describe the bug**
Unable to login by phone number after updatring v2.1.0.

**To Reproduce**
1. Go to 'loing page'
2. Enter my phone number.
3. Click 'Send'
4. Enter login code sent to telegram.
5. See `Something error`

**Expected behavior**
Login successfully.

**Screenshots**
<img width="1458" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/162605164-7d8fc0cf-d7cc-4cb0-b61e-ed15a72bf8ee.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 12.3.1
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 100.0.4896.75

**Additional context**
No log.

**Comment by mgilangjanuar** [comment]
Did you migrate the `dump.20220406.sql`?

**Comment by mzch** [comment]
Oh, I didn't apply it. Now I can login! Thanks @mgilangjanuar ! :)

**Comment by ExtremeMemes** [comment]
@mgilangjanuar How do I migrate the dump?
