### ISSUE TITLE
I can't log in 

### ISSUE THREAD

**Issue by tissole** [mgilangjanuar/teledrive#320]
I'm on Windows 10. I tried to install it by running in git bash
```
chmod +x ./install.manual.sh
./install.manual.sh
```
The app has been installed, I opened the web interface in Firefox and tried in Edge too, I introduced the phone number, the code received and the password, but I get an error and I can't log in.
```
Error
relation "public.users" does not exist
```

**Comment by mgilangjanuar** [comment]
Import your schema: https://teledriveapp.com/docs/Installation/manual#database-preparation

I'll update the script

**Comment by tissole** [comment]
It gives me errors, I'll wait for the updated script. Thanks!

**Comment by tissole** [comment]
The issue has been fixed with this command `yarn server prisma migrate deploy`, before running the app with  `cd server && node dist/index.js`. Thank you for the help.
