### ISSUE TITLE
Teledrive try connect to API from localhost instead of server domain

### ISSUE THREAD

**Issue by TartamaFajak21** [mgilangjanuar/teledrive#338]
I have installed Teledrive in manual mode (Experimental) with Nginx as reverse proxy.
Teledrive instead is trying to load API from localhost:4000 as you can see
![errorlocalhost](https://user-images.githubusercontent.com/86473297/164571472-39347738-d286-4c2f-93e6-6e6c69bc213e.PNG)
.

**Comment by mgilangjanuar** [comment]
Change `REACT_APP_API_URL` to your domain name and rebuild the app

**Comment by TartamaFajak21** [comment]
> Change `REACT_APP_API_URL` to your domain name and rebuild the app

Thanks it worked
