### ISSUE TITLE
Ability to upload a folder

### ISSUE THREAD

**Issue by somnathrakshit** [mgilangjanuar/teledrive#356]
**Is your feature request related to a problem? Please describe.**
Currently, I am unable to upload a folder at once. I am talking about the Upload folder feature that is available on Google drive.

**Describe the solution you'd like**
Ability to upload a folder

**Comment by greengeckowizard** [comment]
Drag n drop folder isn't added yet but if you hit the plus folder icon and then hit upload you can upload a folder through there.

**Comment by somnathrakshit** [comment]
Thank you! That works for me.
