### ISSUE TITLE
Failed-No file

### ISSUE THREAD

**Issue by thecsa** [mgilangjanuar/teledrive#371]
Mp3, video, pdf, epub etc. Whenever I want to download something, it's always "failed-no file". Also no video and mp3 preview. I'm using Heroku. I'm accessing via Chrome. All this is also happening on the android mobile side.

**Comment by thecsa** [comment]
![Imgur](https://imgur.com/pQUK2ha.jpg)

**Comment by vishvaluke** [comment]
I am also facing the same issue. Whenever I try to download a file 'Failed - No file' error message is been shown 

@mgilangjanuar brother, are we missing something.
