### ISSUE TITLE
Unable to deploy on Heroku due to TOS violation 

### ISSUE THREAD

**Issue by sangalaviral** [mgilangjanuar/teledrive#373]
**Describe the bug**
Heroku says 
"Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**To Reproduce**
Try to deploy the app on Heroku

**Expected behavior**
App getting deployed

**Screenshots**
![image](https://user-images.githubusercontent.com/15628421/174722057-f927da25-3394-46b3-9098-6da0992e0262.png)

**Comment by OscarCMD** [comment]
## The teledrive main repo is banned on heroku, so what you can do is the following:

### 1. Fork the teledrive repo



![image](https://user-images.githubusercontent.com/42100404/174849074-015347fc-b462-4ee6-8256-31f3bea6133d.png)

### 2. Copy your forked repo url

> _Make sure to copy the entire url with "https://"_

![image](https://user-images.githubusercontent.com/42100404/174852992-495c9408-26bf-4337-9c96-1b26d1294190.png)

### 3. Use this heroku template url

> _Replace "{forked-repo-url}" with your forked repo url_

#### `https://dashboard.heroku.com/new?template={forked-repo-url}`



# Done, now you can deploy teledrive on heroku without issue

**Comment by greengeckowizard** [comment]
@OscarCMD  Thank you for making instructions it helps a lot when people are deploying through Heroku :blush:

**Comment by OscarCMD** [comment]
@greengeckowizard Grateful to give help, feel free to post this guide anywhere if you want so that people can get to it more easily. For instance, on [the one click deployment button on github readme](https://github.com/mgilangjanuar/teledrive#deploy-to-heroku) and on [the webpage.](http://teledriveapp.com/docs/Deployment/heroku/#one-click-deployment), YT, Telegram Channel ...

Thanks to the teledrive team for such a great product.

**Comment by greengeckowizard** [comment]
closing bug as the guide shows how to fix it, Thanks again for making this guide. @OscarCMD

**Comment by mdshawn** [comment]
-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 18.x...
       Downloading and installing node 18.15.0...
       Using default npm version: 9.5.0
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > @ideasio/add-to-homescreen-react@1.0.10" has incorrect peer dependency "react@16.13.1".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > @ideasio/add-to-homescreen-react@1.0.10" has incorrect peer dependency "react-dom@16.13.1".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > antd-country-phone-input@4.3.1" has unmet peer dependency "rc-select@^12.1.13".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-loading-screen@0.0.17" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-otp-input@2.4.0" has incorrect peer dependency "react@^16.2.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-otp-input@2.4.0" has incorrect peer dependency "react-dom@^16.2.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-icons@2.2.7" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-icons@2.2.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-progress-bar.js@0.2.3" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-progress-bar.js@0.2.3" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > react-pdf@5.0.0" has incorrect peer dependency "react@^16.3.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > react-pdf@5.0.0" has incorrect peer dependency "react-dom@^16.3.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*".
       warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > react-pdf > worker-loader@3.0.8" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
       warning Workspaces can only be enabled in private projects.
       warning Workspaces can only be enabled in private projects.
       [4/4] Building fresh packages...
       Done in 94.75s.
       
-----> Build
       Running build (yarn)
       yarn run v1.22.19
       $ yarn workspaces run build
       
       > web
       $ react-scripts build
       Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/build_6e213c00/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:471:10)
    at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:503:5
    at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:358:12
    at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/tmp/build_6e213c00/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /tmp/build_6e213c00/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/tmp/build_6e213c00/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/tmp/build_6e213c00/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:417:16)
    at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:452:10
    at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:323:13
    at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /tmp/build_6e213c00/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Node.js v18.15.0
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /tmp/build_6e213c00/.heroku/node/bin/node
Arguments: /tmp/build_6e213c00/.heroku/yarn/lib/cli.js run build
Directory: /tmp/build_6e213c00/web
Output:
       info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command.
error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by mysubcult** [comment]
> -----> Building on the Heroku-22 stack -----> Determining which buildpack to use for this app -----> Node.js app detected
> 
> -----> Creating runtime environment
> 
> ```
>    NPM_CONFIG_LOGLEVEL=error
>    USE_YARN_CACHE=true
>    NODE_VERBOSE=false
>    NODE_ENV=production
>    NODE_MODULES_CACHE=true
> ```
> 
> -----> Installing binaries engines.node (package.json): unspecified engines.npm (package.json): unspecified (use default) engines.yarn (package.json): unspecified (use default)
> 
> ```
>    Resolving node version 18.x...
>    Downloading and installing node 18.15.0...
>    Using default npm version: 9.5.0
>    Resolving yarn version 1.22.x...
>    Downloading and installing yarn (1.22.19)
>    Installed yarn 1.22.19
> ```
> 
> -----> Installing dependencies Installing node modules (yarn.lock) yarn install v1.22.19 [1/4] Resolving packages... [2/4] Fetching packages... [3/4] Linking dependencies... warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > @ideasio/add-to-homescreen-react@1.0.10" has incorrect peer dependency "react@16.13.1". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > @ideasio/add-to-homescreen-react@1.0.10" has incorrect peer dependency "react-dom@16.13.1". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > antd-country-phone-input@4.3.1" has unmet peer dependency "rc-select@^12.1.13". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-loading-screen@0.0.17" has incorrect peer dependency "react@^16.0.0 || ^15.0.0 || ^0.14.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-otp-input@2.4.0" has incorrect peer dependency "react@^16.2.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-otp-input@2.4.0" has incorrect peer dependency "react-dom@^16.2.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-virtualized@9.22.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-virtualized@9.22.3" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > @testing-library/user-event@12.8.3" has unmet peer dependency "@testing-library/dom@>=7.21.4". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-icons@2.2.7" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-icons@2.2.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16.0.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-progress-bar.js@0.2.3" has incorrect peer dependency "react@^15.0.0 || ^16.0.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-progress-bar.js@0.2.3" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > react-pdf@5.0.0" has incorrect peer dependency "react@^16.3.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > react-pdf@5.0.0" has incorrect peer dependency "react-dom@^16.3.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-chat-elements > react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*". warning "workspace-aggregator-e838a8fd-a53c-4024-9f71-8fe34a189660 > web > react-doc-viewer > react-pdf > worker-loader@3.0.8" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0". warning Workspaces can only be enabled in private projects. warning Workspaces can only be enabled in private projects. [4/4] Building fresh packages... Done in 94.75s.
> 
> -----> Build Running build (yarn) yarn run v1.22.19 $ yarn workspaces run build
> 
> ```
>    > web
>    $ react-scripts build
>    Creating an optimized production build...
> ```
> 
> Error: error:0308010C:digital envelope routines::unsupported at new Hash (node:internal/crypto/hash:71:19) at Object.createHash (node:crypto:133:10) at module.exports (/tmp/build_6e213c00/node_modules/webpack/lib/util/createHash.js:135:53) at NormalModule._initBuildHash (/tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:417:16) at handleParseError (/tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:471:10) at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:503:5 at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:358:12 at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:373:3 at iterateNormalLoaders (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:214:10) at iterateNormalLoaders (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:221:10) at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:236:3 at runSyncOrAsync (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:130:11) at iterateNormalLoaders (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:232:2) at Array. (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:205:4) at Storage.finished (/tmp/build_6e213c00/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16) at /tmp/build_6e213c00/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9 /tmp/build_6e213c00/node_modules/react-scripts/scripts/build.js:19 throw err; ^ Error: error:0308010C:digital envelope routines::unsupported at new Hash (node:internal/crypto/hash:71:19) at Object.createHash (node:crypto:133:10) at module.exports (/tmp/build_6e213c00/node_modules/webpack/lib/util/createHash.js:135:53) at NormalModule._initBuildHash (/tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:417:16) at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:452:10 at /tmp/build_6e213c00/node_modules/webpack/lib/NormalModule.js:323:13 at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:367:11 at /tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:233:18 at context.callback (/tmp/build_6e213c00/node_modules/loader-runner/lib/LoaderRunner.js:111:13) at /tmp/build_6e213c00/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 { opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], library: 'digital envelope routines', reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED' } Node.js v18.15.0 error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. error Command failed. Exit code: 1 Command: /tmp/build_6e213c00/.heroku/node/bin/node Arguments: /tmp/build_6e213c00/.heroku/yarn/lib/cli.js run build Directory: /tmp/build_6e213c00/web Output: info Visit https://yarnpkg.com/en/docs/cli/workspaces for documentation about this command. error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. -----> Build failed
> 
> ```
>    We're sorry this build is failing! You can troubleshoot common issues here:
>    https://devcenter.heroku.com/articles/troubleshooting-node-deploys
>    
>    Some possible problems:
>    
>    - Node version not specified in package.json
>      https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
>    
>    Love,
>    Heroku
> ```
> 
> ! Push rejected, failed to compile Node.js app. ! Push failed

any solution?
