### ISSUE TITLE
SYNC

### ISSUE THREAD

**Issue by Eikosa** [mgilangjanuar/teledrive#379]
Export and import should be automatic.
![image](https://user-images.githubusercontent.com/20538090/175796881-c4953a7d-151a-4439-81f1-5c8ba91c71e0.png)
Upload and download this file if necessary.

**Comment by greengeckowizard** [comment]
Sync is already a function but you can only )sync up to 50 files its in the dashboard 
![image](https://user-images.githubusercontent.com/34012548/185263151-e97c807f-df29-439f-9f3a-0a42e2787920.png)
