### ISSUE TITLE
Remote Upload 

### ISSUE THREAD

**Issue by randomloops** [mgilangjanuar/teledrive#380]
A interface to upload files from Urls would be good, like from direct download link, Google drive, etc.

Also if I have files on my telegram channel/saved messages, I would like to point files from there too, so I can access them from website also.

**Comment by BarrenWardo** [comment]
@randomloops use that chat like button in the lower right corner then search for your TG user ID then select the files it'll get added.

**Comment by BarrenWardo** [comment]
> @randomloops use that chat like button in the lower right corner then search for your TG user ID then select the files it'll get added.

This for your saved messages/chats.
