### ISSUE TITLE
Docker fails to deploy teledrive

### ISSUE THREAD

**Issue by OscarCMD** [mgilangjanuar/teledrive#387]
**Describe the bug**
The [install.docker.sh](http://install.docker.sh/) script creates a base64 password that causes docker not to deploy.

**To Reproduce**
On the install.docker.sh script [there is a line](https://github.com/mgilangjanuar/teledrive/blob/6c7ef8fd9e7d2e5faba917569e08856a8b402f87/install.docker.sh#L24) that says the following:

```bash
DB_PASSWORD=$(node -e "console.log(require('crypto').randomBytes(48).toString('base64'));")
```

This creates a base64 password for postgresql that [docker-compose.yml](https://github.com/mgilangjanuar/teledrive/blob/6c7ef8fd9e7d2e5faba917569e08856a8b402f87/docker/docker-compose.yml#L20) fails to use it as there is a url that uses the password, and the password usually is generated with “/” and “+” characters which make teledrive not to deploy.

**Expected behavior**
Teledrive to deploy on docker.

**Screenshots**
![image](https://user-images.githubusercontent.com/42100404/177057379-724bb863-43f6-4038-a729-3ae2831c6cad.png)

**Comment by greengeckowizard** [comment]
Could you please make the code changes to the staging branch? We'll add your changes in the next update. Thank you for solving a bug :+1:
