### ISSUE TITLE
Docker Container not starting after build

### ISSUE THREAD

**Issue by greengeckowizard** [mgilangjanuar/teledrive#388]
After building and initiating docker container docker_teledrive_1 doesn't seem to stay running after build other containers seem active checking with docker ps

**Comment by OscarCMD** [comment]
As said on #387, this was a bug on password generation for postgresql database, the fix was merged on staging branch #389, try to fresh install using staging branch.

**Comment by greengeckowizard** [comment]
Thank you for fixing this bug @OscarCMD I'll close this bug due to this being fixed :+1:
