### ISSUE TITLE
[HEROKU] Item could not be created:

### ISSUE THREAD

**Issue by shirooo39** [mgilangjanuar/teledrive#396]
I followed [this instruction](https://teledriveapp.com/docs/Deployment/heroku) but as the documentations are extremely poorly written, I ended up with this:

```
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.
```

**Comment by OscarCMD** [comment]
[Try this](https://github.com/mgilangjanuar/teledrive/issues/373#issuecomment-1162007141)

**Comment by shirooo39** [comment]
> [Try this](https://github.com/mgilangjanuar/teledrive/issues/373#issuecomment-1162007141)

it has been 3 days and I already kind of forgot how to do this.
do I still need to manually pull the repo first, or just deploy the template?

**Comment by OscarCMD** [comment]
> > [Try this](https://github.com/mgilangjanuar/teledrive/issues/373#issuecomment-1162007141)
> 
> it has been 3 days and I already kind of forgot how to do this. do I still need to manually pull the repo first, or just deploy the template?

You have to deploy the template using your teledrive forked repo, just [follow this steps](https://github.com/mgilangjanuar/teledrive/issues/373#issuecomment-1162007141)

**Comment by shirooo39** [comment]
> > > [Try this](https://github.com/mgilangjanuar/teledrive/issues/373#issuecomment-1162007141)
> > 
> > 
> > it has been 3 days and I already kind of forgot how to do this. do I still need to manually pull the repo first, or just deploy the template?
> 
> You have to deploy the template using your teledrive forked repo, just [follow this steps](https://github.com/mgilangjanuar/teledrive/issues/373#issuecomment-1162007141)

what should fill these with?
- REACT_APP_TG_API_HASH
- REACT_APP_TG_API_ID
- TG_API_HASH
- TG_API_ID

should I just fill them with these?
![image](https://user-images.githubusercontent.com/38461122/180605724-b4b92636-daa3-4ef8-9b3b-40a2c78d8d62.png)
