### ISSUE TITLE
Heroku is not more Free

### ISSUE THREAD

**Issue by Slippy2k** [mgilangjanuar/teledrive#412]
Hello,
Heroku is not more Free! Have you a other Free Alternative for Heroku ?

**Comment by greengeckowizard** [comment]
I recommend oracle free tier.

**Comment by greengeckowizard** [comment]
https://www.oracle.com/cloud/free/

**Comment by Slippy2k** [comment]
https://www.oracle.com is not a good alternative
Is there maybe a guide for https://vercel.app

**Comment by greengeckowizard** [comment]
Vercel doesn't build with our current code. I suggest trying Oracle free tier.

VPS works as well minimum 2gb ram for building 

 Railway:Not working

**Comment by greengeckowizard** [comment]
Closing this since there's nothing we can do to make Heroku free again.
