### ISSUE TITLE
One-click deployment script for CapRover

### ISSUE THREAD

**Issue by somnathrakshit** [mgilangjanuar/teledrive#414]
Can we have a [one-click deployment script](https://github.com/caprover/one-click-apps) for [CapRover](https://github.com/caprover/caprover)? It is a self-hosted Heroku alternative that can be used easily in Oracle Cloud.

**Comment by somnathrakshit** [comment]
[Here is a list of apps](https://github.com/caprover/one-click-apps/tree/master/public/v4/apps) that already have a one-click deployment script

**Comment by greengeckowizard** [comment]
Can you test please.
#!/bin/bash

set -e

echo "Node Version: $(node -v)"
echo "Yarn Version: $(yarn -v)"

if [ ! -f docker/.env ]
then
  echo "Generating docker/.env file..."

  ENV="develop"

  echo "Preparing your keys from https://my.telegram.org/"
  read -p "Enter your TG_API_ID: " TG_API_ID
  read -p "Enter your TG_API_HASH: " TG_API_HASH

  echo "ENV=$ENV" > docker/.env
  echo "TG_API_ID=$TG_API_ID" >> docker/.env
  echo "TG_API_HASH=$TG_API_HASH" >> docker/.env
fi

git reset --hard
git clean -f
git pull origin main

export $(cat docker/.env | xargs)

echo
echo "Build and deploy to CapRover..."
docker build --build-arg REACT_APP_TG_API_ID=$TG_API_ID --build-arg REACT_APP_TG_API_HASH=$TG_API_HASH -t myapp .
caprover deploy --name myapp --image myapp
```

This script assumes that you have already set up a CapRover server and added your app to it. It also assumes that you have set up a Git remote named `origin` for your repository.

To use this script, simply copy and paste it into a file named `deploy.sh` in the root directory of your project. Then, make sure the file is executable (`chmod +x deploy.sh`) and run it with `./deploy.sh`.

This script will generate a `.env` file if it doesn't already exist, prompt you to enter your Telegram API ID and hash, pull the latest changes from the `main` branch, build a Docker image with the specified arguments, and deploy the image to CapRover with the name `myapp`. You can adjust the name and other options as needed.

**Comment by greengeckowizard** [comment]
We're excited to announce the availability of our new experimental CapRover setup script in the staging branch! With this script, you can easily set up and deploy your applications to CapRover, a powerful open-source platform for container management and deployment.

This script is still in the testing phase, and we need your help to make it even better. With your feedback, we can ensure that the script is stable and reliable for all users.

To get started, simply clone the staging branch and run the setup script. You'll be guided through the setup process, and you can start deploying your Teledrive to CapRover in no time.

We invite you to try out the setup script and share your feedback with us. Your input is critical in helping us improve the script and make it the best possible solution for CapRover setup and deployment.

**Comment by greengeckowizard** [comment]
We'll be working to make the one-click experience in no time!
