### ISSUE TITLE
I can download a file only once, any more and it fails to download it.

### ISSUE THREAD

**Issue by Mehmuod** [mgilangjanuar/teledrive#416]
I can download a file I uploaded to teledrive only once, if I try to redownload it, it fails even though I can download it from the telegram app just fine.

**To Reproduce**
Right click a file and download.

**Expected behavior**
Ability to redownload any file as many times as desired.

**Desktop
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [105.0.5195.102]

**Comment by greengeckowizard** [comment]
Fixed in staging.
