### ISSUE TITLE
[REQUEST] Photo Backup for iPhone

### ISSUE THREAD

**Issue by manm15** [mgilangjanuar/teledrive#418]
Is it possible to make a photo backup app for iPhone? It can be a .ipa file so it can be like Google Photos. If it works with the web app it will be even better. Thank you so much!

**Comment by andriilive** [comment]
Try [rclone](https://rclone.org) auto-upload from iCloud Drive

**Comment by manm15** [comment]
https://github.com/rclone/rclone/issues/5829#issuecomment-1153329730

**Comment by andriilive** [comment]
> https://github.com/rclone/rclone/issues/5829#issuecomment-1153329730

Hm I thought the teledrive provides webdav in self hosted version, But unf no.

Sure thing the rclone will not spend their time to develop integrations for unstable solutions like this one. 

The simplest approach I can imagine u can try, (if u have both Mac and IPhone) I guess is to use iCloud storage as a buffer. Try something like this:

- Turn the iCloud Photos upload on IPhone & Mac
- At Mac create Hazel or Shortcuts automation running every hour with something like: when connected to wifi if Photos lib is not empty -> copy all its contents to temporary macs folder and erase copied from the Photos lib.
- then trigger a script to send files via teledrives api https://www.postman.com/restfireteam/workspace/mgilangjanuar/folder/1778529-f0f1f434-b35b-4e38-b3cf-2ddf12cccb46?ctx=documentation, u can play around with sync and post files methods.
- clean up the temp folder if  file upload result was successful

Mb it's enough just to create a Shortcut on a IPhone, but I'm not sure about that, never triggered an api calls from those.

**Comment by greengeckowizard** [comment]
Mobile App is in development I'll close this for now but as of now you can upload through your devices browser.
