### ISSUE TITLE
The problem is that a file that weighs more than 2 GB cannot be downloaded.

### ISSUE THREAD

**Issue by NightSommelier** [mgilangjanuar/teledrive#425]
**Describe the bug**
I uploaded a file with the .exe extension to TeleDrive, the file weight is 1.9 GB. I can’t download ... The download of the file ends, then it starts downloading again. And so it can be in a circle.

**Desktop (please complete the following information):**
 - OS: Docker Container
 - Browser Chrome
 - Version 106.0.5249.119

**Additional context**
Smaller files are downloaded without problems, and files that are broken into parts are trying to download again.

**Comment by greengeckowizard** [comment]
This bug is being worked on thanks for letting us know!

**Comment by greengeckowizard** [comment]
Files should be able to be downloaded over 2gb but a corrupt file is the output (currently in staging).
