### ISSUE TITLE
Run without docker

### ISSUE THREAD

**Issue by wawan-ikhwan** [mgilangjanuar/teledrive#431]
How do I run server without using docker, I have small server that only for teledrive purpose, so why should I install docker.

**Comment by red0888** [comment]
Docker is actually really lightweight. Only a few extra MB storage is required since the image includes the OS. Other than that the overhead for docker itself is really low

**Comment by greengeckowizard** [comment]
If you see the website you don't have to use docker for your server you can use manual installation.
https://teledriveapp.com/docs/Installation/manual
