### ISSUE TITLE
Unable to deploy to Heroku as nodejs version not specified

### ISSUE THREAD

**Issue by Aeslyy** [mgilangjanuar/teledrive#433]
Build failed
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
        !     Push rejected, failed to compile Node.js app.
        !     Push failed`
 
 What should I do? Which solution?

**Comment by greengeckowizard** [comment]
Should be fixed in Staging branch.

**Comment by Aeslyy** [comment]
Thanks! 
I got it, thank you very much!

**Comment by Aeslyy** [comment]
> Maybe it can be useful: Check my package.json and update your .json like that.
> 
> `{ "name": "teledrive", "version": "2.5.2", "engines": { "node": "16.x" }, "repository": "git@github.com:mgilangjanuar/teledrive.git", "author": "M Gilang Januar <mgilangjanuar@teledriveapp.com>", "license": "MIT", "private": true, "scripts": { "web": "yarn workspace web", "server": "yarn workspace api", "api": "yarn workspace api", "build": "yarn workspaces run build", "start": "cd api && node dist/index.js", "docs": "USE_SSH=true cd docs && yarn deploy" }, "workspaces": [ "web", "api" ], "dependencies": {} }`

Thanks!
I got it, thank you very much!
