### ISSUE TITLE
Option to change the channel where the file is uploaded 

### ISSUE THREAD

**Issue by Pablohn26** [mgilangjanuar/teledrive#435]
**Is your feature request related to a problem? Please describe.**
By default, the attachments are uploaded to Telegram personal messages. Would be possible to configure another channel? 

**Describe the solution you'd like**
A place to select the channel where the files are going to be uploaded

**Describe alternatives you've considered**
A variable to write the ID of the channel where the data should be uploaded to

**Additional context**
I do not want to mix my personal messages with my teledrive files

**Comment by greengeckowizard** [comment]
If you go in settings you should have an option for changing where you want to save.

**Comment by Pablohn26** [comment]
Ok thanks 

![imagen](https://user-images.githubusercontent.com/1228418/219719836-fbc3d226-079b-488a-8d0c-ecdcf30cafa8.png)
