### ISSUE TITLE
Experimental Features Login Issue 

### ISSUE THREAD

**Issue by heypious** [mgilangjanuar/teledrive#441]
**Describe the bug**
No QR code is generated or OTP is sent when asked to login (only when trying to enable experimental features)

**To Reproduce**
1. Go to 'Teledrive'
2. Click on 'Profile-Settings'
3. Scroll down to 'Danger Zone'
4. Click Experimental.
5. Choose to login via any method. (It Won't Work)

**Expected behavior**
It should be same as main login where you can login via QR or OTP.

**Screenshots**
![image](https://user-images.githubusercontent.com/59928150/221164819-65f170db-bc8a-4fd7-85ec-c4c4b4d5c41b.png)
QR code never loads.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome and Firefox
 - Version: v2.5.2

**Smartphone (please complete the following information):**
 - Device: Realme 6
 - OS: Android 12 (Custom Rom)
 - Browser: Google Chrome and Firefox
 - Version: v2.5.2

**Additional context**
Teledrive is deployed using the docker (Method- Directly Build Using Script)

**Comment by greengeckowizard** [comment]
Are you running it without https?

**Comment by greengeckowizard** [comment]
Duplicate entry #430
