### ISSUE TITLE
Build from Dockerfile is failing

### ISSUE THREAD

**Issue by albertopasqualetto** [mgilangjanuar/teledrive#454]
Build from Dockerfile is failing.

- [ERR_OSSL_EVP_UNSUPPORTED](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported) can be resolved with `export NODE_OPTIONS=--openssl-legacy-provider`added  in the Dockerfile
- [Build error You must provide the URL of lib/mappings.wasm](https://github.com/parcel-bundler/parcel/issues/8005) can be resolved with `export NODE_OPTIONS=--no-experimental-fetch` added in the Dockerfile
- "Browserslist: caniuse-lite is outdated" can be resolved by removing all lines in files `*.lock` as [workaround](https://github.com/facebook/create-react-app/issues/6708#issuecomment-488392836)

Please resolve these problems directly in your code.

(I am using an arm64 VM from Oracle cloud)

**Comment by greengeckowizard** [comment]
Fixed in Staging branch

**Comment by albertopasqualetto** [comment]
Your commit is not affecting the Dockerfile, I suggest you to add `ENV NODE_OPTIONS="--openssl-legacy-provider --no-experimental-fetch"` to the it, instead.

**Comment by ACHIYA96** [comment]
Hi @albertopasqualetto. 
I'm having some trouble to get this set up in Oracle Cloud. Will you be able to help me? 
Thanks in advance.

**Comment by albertopasqualetto** [comment]
> Hi @albertopasqualetto. 
> I'm having some issues when I tried to get this set up in Oracle Cloud. Will you be able to help me? 
> Thanks in advance.

Hello, which issues are you encountering?
I have builded and ran manually teledrive on docker compose. If you want I can post my docker-compose.yml

P.S.: note that this issue is partially no more valid due to some new fixes from latest commits.

**Comment by ACHIYA96** [comment]
> > Hi @albertopasqualetto.
> > I'm having some issues when I tried to get this set up in Oracle Cloud. Will you be able to help me?
> > Thanks in advance.
> 
> Hello, which issues are you encountering? I have builded and ran manually teledrive on docker compose. If you want I can post my docker-compose.yml
> 
> P.S.: note that this issue is partially no more valid due to some new fixes from latest commits.

Thank you so much for the reply. How can I contact you? 

After running “ docker-compose up -d” I got the following errors. And I might need your help with opening ports on my VPS too. 

Last bit of the log;

“ 
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
Killed
[4/5] Linking dependencies...
The command '/bin/sh -c yarn install --network-timeout 1000000' returned a non-zero code: 137
ERROR: Service 'teledrive' failed to build : Build failed “
