### ISSUE TITLE
Startup error on update 6ac0184

### ISSUE THREAD

**Issue by NightSommelier** [mgilangjanuar/teledrive#458]
The last update 6ac0184 is clearly incomplete. It gives out an error:

<img width="1022" alt="Screenshot 2023-04-09 at 12 59 54" src="https://user-images.githubusercontent.com/2665877/230766549-a0c3244f-2737-4a3d-81ed-c3d37adc6724.png">

**Comment by greengeckowizard** [comment]
I'm experimenting with different package versions. Also this is normal staging branch isn't always stable its testing  new features and code fixing. This is an issue that's unnecessary to make. Thank you for your concern.

**Comment by greengeckowizard** [comment]
Ok to prevent any controversy I made a experiment branch which can absolutely not work (testing unstable) while staging is second to close to being as stable as main branch. I want to thank you again for your interest to try staging it is now usable while still not fully stable.
