### ISSUE TITLE
Let's talk about this

### ISSUE THREAD

**Issue by oddmario** [mgilangjanuar/teledrive#96]
Hello,

So this project brought my attention and I like the idea, however let's talk about it for a little while - I know GitHub issues ain't the right place to do that but I thought it'd be the most active discussion station that we can discuss that on.

Alright so you're stating on your website that Telegram **__promised__** they'll provide unlimited cloud storage free, forever. I couldn't really find any indication that it was a promise, to me it was just a normal Tweet in which they said that they provide unlimited cloud storage, maybe it's just temporarily?
And let's suppose that they promised, we all know that promises never work in our world (if we're being honest)... Remember how Microsoft promised that Windows 10 was gonna be the last release of Windows? well we have Windows 11 now.
Well and I, I personally provide a free service and in the start we almost promised that we're gonna provide a unique feature in our service (free 24/7 Minecraft hosting), however we couldn't handle this due to the nature of Minecraft servers.. they consume a lot of resources.

I know we can't compare my service with a company like Telegram, but everything has a limit anyway or am I wrong?

Like is Telegram aware of this project? you can't just sell some paid plans already without asking for their permission first. What if Telegram change their "promise" one day? that's gonna be some shocking news to everyone using TeleDrive.

And since I already opened an issue here, there's one more thing that I'd like to report, the file picker doesn't work on phone like I'm unable to upload any files on the phone interface
**EDIT:** it seems the file uploader is actually a folder uploader, is that the expected behaviour?

Thank you for reading my issue

**Comment by mgilangjanuar** [comment]
I can't talk more about this and I can't predict the future. But, here's our conversation with the Telegram representative with me: https://github.com/mgilangjanuar/teledrive/discussions/60

Have fun, for now 🤣

**Comment by oddmario** [comment]
> I can't talk more about this and I can't predict the future. But, here's our conversation with the Telegram representative: #60
> 
> Have fun, for now 🤣

ok I don't know why your reply sounded as if I were arguing w you but that's alright.
anyway the issue you linked to doesn't answer any of what I asked but that's also alright
and yeah you apparently ignored my bug report but you know what that is..

**Comment by mgilangjanuar** [comment]
Oh no, I think you have a misunderstanding here. I can't answer all of your questions because of the time. I should work and fix bugs on all of my projects. In short, I think this is only the fun project that I made for my side job. So, you can use it or leave it. That's it 🤗

Anw, I re-create your issue in a better format and proper title for better search for another contributors :)
